[package]
name = "trie"
version = "0.1.0"
authors = ["brector <brector@crabel.com>"]
edition = "2018"

[dependencies]
uuid = { version = "0.7", features = ["v4"]}
lifeguard = { version = "0.5.2" }
fnv = "1.0.6"